#!/bin/sh
# pin-db.sh — interactively pin a DB entrypoint to a specific container (or unpin),
# via the Traefik FILE provider (deterministic; wins over docker label routers).
#
#   sh netconnect/pin-db.sh pin   [ep]   # pin   (no ep -> pick a DB first)
#   sh netconnect/pin-db.sh unpin [ep]   # unpin (no ep -> pick a pinned DB)
#   ep = postgres|mysql|redis|mongodb
#
# A pin writes dynamic/pin-<ep>.yaml (a high-priority TCP router → <container>,
# beating the -1 of the docker HostSNI(`*`) routers so routing is deterministic),
# records it in netconnect/pins.conf (so the sidecar keeps <container> attached),
# attaches <container> to the gateway network, and restarts traefik + netconnect.
# Run from the repo root (via `make pin` / `make unpin`).
set -u

NET=traefik-gateway-net
PRIORITY=9999
DB_EPS="postgres mysql redis mongodb"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PINS="$SCRIPT_DIR/pins.conf"
DYN="$(cd "$SCRIPT_DIR/.." && pwd)/dynamic"
COMPOSE="docker compose"
API="http://localhost:8080/api/tcp/routers"

mode="${1:-pin}"
ep="${2:-}"
case "$mode" in pin|unpin) ;; *) echo "用法: pin-db.sh <pin|unpin> [postgres|mysql|redis|mongodb]"; exit 1 ;; esac

port_of() {  # echo the standard port for an entrypoint
  case "$1" in
    postgres) echo 5432 ;;  mysql) echo 3306 ;;
    redis)    echo 6379 ;;  mongodb) echo 27017 ;;
    *) return 1 ;;
  esac
}

# --- helpers (host-side docker) -------------------------------------------
claims_ep() {  # $1=container $2=ep -> 0 if it declares entrypoints=<ep>
  docker inspect "$1" --format '{{json .Config.Labels}}' 2>/dev/null \
    | grep -oE '"traefik\.tcp\.routers\.[^"]*\.entrypoints":"[^"]*"' \
    | sed -E 's/.*:"([^"]*)"$/\1/' | tr ',' '\n' | grep -qx "$2"
}
attached() {
  [ -n "$(docker inspect "$1" --format "{{if index .NetworkSettings.Networks \"$NET\"}}1{{end}}" 2>/dev/null)" ]
}
workdir() {
  d="$(docker inspect "$1" --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' 2>/dev/null)"
  [ -n "$d" ] && echo "$d" || echo "-"
}
claimants_of() {  # $1=ep -> names of running enable=true containers claiming it
  for c in $(docker ps --filter label=traefik.enable=true --format '{{.Names}}'); do
    claims_ep "$c" "$1" && echo "$c"
  done
}
pin_of() {  # $1=ep -> pinned container (empty if none)
  grep -E "^[[:space:]]*$1[[:space:]]*=" "$PINS" 2>/dev/null \
    | grep -vE '^[[:space:]]*#' | sed -E "s/^[^=]*=[[:space:]]*//; s/[[:space:]]*\$//" | tail -n1
}
set_pin() {  # $1=ep $2=container ("" to just remove the line)
  tmp="$PINS.tmp.$$"
  grep -vE "^[[:space:]]*$1[[:space:]]*=" "$PINS" 2>/dev/null > "$tmp" || true
  [ -n "$2" ] && echo "$1=$2" >> "$tmp"
  mv "$tmp" "$PINS"
}
write_pin_file() {  # $1=ep $2=container $3=port
  cat > "$DYN/pin-$1.yaml" <<YAML
# Generated by 'make pin DB=$1'. High-priority TCP router that deterministically
# pins the $1 entrypoint (:$3) to '$2', overriding docker label routers.
# Remove with 'make unpin DB=$1'.
tcp:
  routers:
    pin-$1:
      entryPoints: ["$1"]
      rule: "HostSNI(\`*\`)"
      priority: $PRIORITY
      service: pin-$1
  services:
    pin-$1:
      loadBalancer:
        servers:
          - address: "$2:$3"
YAML
}
apply() {
  echo "→ 套用中（重啟 traefik 讀取 dynamic/、netconnect 重讀 pins.conf）…"
  $COMPOSE restart traefik netconnect >/dev/null 2>&1 \
    || { echo "✗ 重啟失敗，gateway 有起來嗎？（make up）"; exit 1; }
  sleep 4
}
show_status() {
  cid="$($COMPOSE ps -q netconnect 2>/dev/null)"
  [ -n "$cid" ] && docker exec "$cid" sh /netconnect/admission.sh check
}

# --- step 1: choose the DB entrypoint if not given ------------------------
if [ -z "$ep" ]; then
  if [ "$mode" = unpin ]; then echo "選擇要解除 pin 的 DB："; else echo "選擇 DB 類型："; fi
  i=0; eps=""
  for e in $DB_EPS; do
    if [ "$mode" = unpin ]; then
      p="$(pin_of "$e")"; [ -n "$p" ] || continue
      i=$((i + 1)); eps="$eps $e"
      printf '  %d) %-9s → 目前 pin: %s\n' "$i" "$e" "$p"
    else
      set -- $(claimants_of "$e"); c=$#
      [ "$c" -gt 0 ] || continue
      i=$((i + 1)); eps="$eps $e"
      p="$(pin_of "$e")"; extra=""; [ -n "$p" ] && extra=" (目前 pin: $p)"
      printf '  %d) %-9s → %d 個候選%s\n' "$i" "$e" "$c" "$extra"
    fi
  done
  if [ "$i" -eq 0 ]; then
    if [ "$mode" = unpin ]; then echo "目前沒有任何 pin。"; else
      echo "沒有任何容器宣告 DB entrypoint（traefik.tcp.routers.*.entrypoints=postgres|mysql|redis|mongodb）。"; fi
    exit 0
  fi
  printf '選擇 (1-%d, q=放棄): ' "$i"
  read dbchoice
  case "$dbchoice" in
    q|Q|"")   echo "已放棄，未變更。"; exit 0 ;;
    *[!0-9]*) echo "無效輸入，未變更。"; exit 1 ;;
  esac
  if [ "$dbchoice" -lt 1 ] || [ "$dbchoice" -gt "$i" ]; then echo "編號超出範圍，未變更。"; exit 1; fi
  # shellcheck disable=SC2086
  set -- $eps; shift $((dbchoice - 1)); ep="$1"
fi

port="$(port_of "$ep")" || { echo "未知 entrypoint: $ep（postgres|mysql|redis|mongodb）"; exit 1; }
PIN_FILE="$DYN/pin-$ep.yaml"

# --- unpin ----------------------------------------------------------------
if [ "$mode" = unpin ]; then
  cur="$(pin_of "$ep")"
  if [ -z "$cur" ] && [ ! -f "$PIN_FILE" ]; then echo "[$ep] 目前沒有 pin，無需處理。"; exit 0; fi
  set_pin "$ep" ""
  rm -f "$PIN_FILE"
  echo "已移除 pin：${ep}（原本釘在 '${cur:-?}'）→ 回到 reject-extras 先搶先贏。"
  apply
  show_status
  exit 0
fi

# --- step 2: choose the instance -----------------------------------------
echo "候選 $ep instances（宣告 entrypoints=$ep 的容器）:"
i=0; names=""
for n in $(claimants_of "$ep"); do
  i=$((i + 1)); names="$names $n"
  img="$(docker inspect "$n" --format '{{.Config.Image}}' 2>/dev/null)"
  st="-"; attached "$n" && st="[on gateway-net]"
  printf '  %d) %-18s %-14s %-30s %s\n' "$i" "$n" "$img" "$(workdir "$n")" "$st"
done
if [ "$i" -eq 0 ]; then echo "  (無：目前沒有容器宣告 entrypoints=$ep)"; exit 0; fi

cur="$(pin_of "$ep")"
[ -n "$cur" ] && echo "目前 pin：$ep = $cur"

printf '選擇要 pin 的編號 (1-%d，u=移除pin，q=放棄): ' "$i"
read choice
case "$choice" in
  q|Q|"")   echo "已放棄，未變更。"; exit 0 ;;
  u|U)      set_pin "$ep" ""; rm -f "$PIN_FILE"; echo "已移除 pin：${ep}。"; apply; show_status; exit 0 ;;
  *[!0-9]*) echo "無效輸入，未變更。"; exit 1 ;;
esac
if [ "$choice" -lt 1 ] || [ "$choice" -gt "$i" ]; then echo "編號超出範圍，未變更。"; exit 1; fi

# shellcheck disable=SC2086
set -- $names; shift $((choice - 1)); sel="$1"

set_pin "$ep" "$sel"
write_pin_file "$ep" "$sel" "$port"
docker network connect "$NET" "$sel" 2>/dev/null || true   # make it routable now
echo "→ pin $ep = ${sel}（dynamic/pin-$ep.yaml, priority ${PRIORITY}）"
apply
if curl -s "$API" 2>/dev/null | grep -q "pin-$ep@file"; then
  echo "✓ file router pin-$ep@file 已載入（priority ${PRIORITY}，壓過 docker 的 -1）"
else
  echo "⚠️  未在 Traefik API 看到 pin-$ep@file，可能沒 reload；試 'make restart'。"
fi
show_status
