#!/bin/sh
# pin-db.sh — interactively pin a DB entrypoint to a specific container (or unpin),
# via the Traefik FILE provider (deterministic; wins over docker label routers).
#
#   sh netconnect/pin-db.sh [postgres|mysql|redis|mongodb]        # interactive pin
#   sh netconnect/pin-db.sh [postgres|mysql|redis|mongodb] unpin  # remove the pin
#
# What a pin does:
#   - writes dynamic/pin-<ep>.yaml: a high-priority TCP router → <container>:<port>
#     (priority beats the -1 of the docker HostSNI(`*`) routers, so routing is
#     deterministic regardless of how many containers carry the label)
#   - records it in netconnect/pins.conf so the sidecar keeps <container> attached
#   - attaches <container> to the gateway network (the file router needs it routable)
#   - restarts traefik (load the new file) and netconnect (re-read pins.conf)
# Run from the repo root (via `make pin` / `make unpin`).
set -u

NET=traefik-gateway-net
PRIORITY=9999
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PINS="$SCRIPT_DIR/pins.conf"
DYN="$(cd "$SCRIPT_DIR/.." && pwd)/dynamic"
COMPOSE="docker compose"
API="http://localhost:8080/api/tcp/routers"

ep="${1:-postgres}"
mode="${2:-pin}"
case "$ep" in
  postgres) port=5432 ;;
  mysql)    port=3306 ;;
  redis)    port=6379 ;;
  mongodb)  port=27017 ;;
  *) echo "用法: pin-db.sh <postgres|mysql|redis|mongodb> [unpin]"; exit 1 ;;
esac
PIN_FILE="$DYN/pin-$ep.yaml"

# --- helpers (host-side docker) -------------------------------------------
claims_ep() {
  docker inspect "$1" --format '{{json .Config.Labels}}' 2>/dev/null \
    | grep -oE '"traefik\.tcp\.routers\.[^"]*\.entrypoints":"[^"]*"' \
    | sed -E 's/.*:"([^"]*)"$/\1/' | tr ',' '\n' | grep -qx "$ep"
}
attached() {
  [ -n "$(docker inspect "$1" --format "{{if index .NetworkSettings.Networks \"$NET\"}}1{{end}}" 2>/dev/null)" ]
}
workdir() {
  d="$(docker inspect "$1" --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' 2>/dev/null)"
  [ -n "$d" ] && echo "$d" || echo "-"
}
current_pin() {
  grep -E "^[[:space:]]*$ep[[:space:]]*=" "$PINS" 2>/dev/null \
    | grep -vE '^[[:space:]]*#' | sed -E "s/^[^=]*=[[:space:]]*//; s/[[:space:]]*\$//" | tail -n1
}
set_pin() {  # $1=container ("" to just remove the line)
  tmp="$PINS.tmp.$$"
  grep -vE "^[[:space:]]*$ep[[:space:]]*=" "$PINS" 2>/dev/null > "$tmp" || true
  [ -n "$1" ] && echo "$ep=$1" >> "$tmp"
  mv "$tmp" "$PINS"
}
write_pin_file() {  # $1=container
  cat > "$PIN_FILE" <<YAML
# Generated by 'make pin DB=$ep'. High-priority TCP router that deterministically
# pins the $ep entrypoint (:$port) to '$1', overriding docker label routers.
# Remove with 'make unpin DB=$ep'.
tcp:
  routers:
    pin-$ep:
      entryPoints: ["$ep"]
      rule: "HostSNI(\`*\`)"
      priority: $PRIORITY
      service: pin-$ep
  services:
    pin-$ep:
      loadBalancer:
        servers:
          - address: "$1:$port"
YAML
}
apply() {  # restart traefik (load file) + netconnect (re-read pins), then verify
  echo "→ 套用中（重啟 traefik 讀取 dynamic/、netconnect 重讀 pins.conf）…"
  $COMPOSE restart traefik netconnect >/dev/null 2>&1 \
    || { echo "✗ 重啟失敗，gateway 有起來嗎？（make up）"; exit 1; }
  sleep 4
}
verify_router_present() {  # confirm the file router actually loaded
  if curl -s "$API" 2>/dev/null | grep -q "pin-$ep@file"; then
    echo "✓ file router pin-$ep@file 已載入（priority ${PRIORITY}，壓過 docker 的 -1）"
  else
    echo "⚠️  未在 Traefik API 看到 pin-$ep@file，可能沒 reload；試 'make restart'。"
  fi
}
show_status() {
  cid="$($COMPOSE ps -q netconnect 2>/dev/null)"
  [ -n "$cid" ] && docker exec "$cid" sh /netconnect/admission.sh check
}

# --- unpin ----------------------------------------------------------------
if [ "$mode" = "unpin" ]; then
  cur="$(current_pin)"
  if [ -z "$cur" ] && [ ! -f "$PIN_FILE" ]; then
    echo "[$ep] 目前沒有 pin，無需處理。"; exit 0
  fi
  set_pin ""
  rm -f "$PIN_FILE"
  echo "已移除 pin：${ep}（原本釘在 '${cur:-?}'）→ 回到 reject-extras 先搶先贏。"
  apply
  show_status
  exit 0
fi

# --- list candidates ------------------------------------------------------
echo "候選 $ep instances（宣告 entrypoints=$ep 的容器）:"
i=0; names=""
for n in $(docker ps --filter label=traefik.enable=true --format '{{.Names}}'); do
  claims_ep "$n" || continue
  i=$((i + 1)); names="$names $n"
  img="$(docker inspect "$n" --format '{{.Config.Image}}' 2>/dev/null)"
  st="-"; attached "$n" && st="[on gateway-net]"
  printf '  %d) %-18s %-14s %-30s %s\n' "$i" "$n" "$img" "$(workdir "$n")" "$st"
done
if [ "$i" -eq 0 ]; then
  echo "  (無：目前沒有容器宣告 traefik.tcp.routers.*.entrypoints=$ep)"
  exit 0
fi

cur="$(current_pin)"
[ -n "$cur" ] && echo "目前 pin：$ep = $cur"

printf '選擇要 pin 的編號 (1-%d，u=移除pin，q=放棄): ' "$i"
read choice
case "$choice" in
  q|Q|"")   echo "已放棄，未變更。"; exit 0 ;;
  u|U)      set_pin ""; rm -f "$PIN_FILE"; echo "已移除 pin：${ep}。"; apply; show_status; exit 0 ;;
  *[!0-9]*) echo "無效輸入，未變更。"; exit 1 ;;
esac
if [ "$choice" -lt 1 ] || [ "$choice" -gt "$i" ]; then
  echo "編號超出範圍，未變更。"; exit 1
fi

# resolve the nth candidate (positional params are 1-indexed)
# shellcheck disable=SC2086
set -- $names
shift $((choice - 1))
sel="$1"

set_pin "$sel"
write_pin_file "$sel"
docker network connect "$NET" "$sel" 2>/dev/null || true   # make it routable now
echo "→ pin $ep = ${sel}（dynamic/pin-$ep.yaml, priority ${PRIORITY}）"
apply
verify_router_present
show_status
